### PR TITLE
swap config to Injector to make sure all hooks etc are run properly

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by DorsetDigital** [comment]
Hi @xini 

Thanks for the PR.  Could I just check what issue this is solving compared to using the existing methods to set the backend provided in the Requirements class itself?   Have you seen some specific problems with the current implementation?

Cheers,
Tim

**Comment by xini** [comment]
Hi Tim,

I found in the past that when not using Injector to replace classes, some things just don't get loaded in properly. 

In this particular case, I have another module, https://github.com/xini/silverstripe-prefix-requirements, that replaces the `ResourceURLGenerator` and uses `Requirements::backend()->getAssetHandler();` to access the generated assets. With your config, the asset handler is always null, when using Injector it's there as expected. I haven't investigated why exactly your version fails. 

Cheers,
Flo

**Comment by ChloeSartorelli** [comment]
I'm inclined to agree with both using the `Injector` and moving the config to yaml.
Moving to yaml makes it a lot easier for people to override your configuration (e.g. if they subclass _this_ backend to add their own enhancements on top), and using the injector ensures that the backend is only ever set the one time - as well as being the generally accepted way of replacing some class with an enhanced subclass.

**Comment by DorsetDigital** [comment]
OK... I've been doing a bit of digging around this issue.   The requirements system is supposed to be 'pluggable' so that you can swap the backend without having to resort to the overhead / trouble of using injector. 

That said, using the "proper" method does seem to cause weird things to happen.. I've found other instances of methods not quite doing what is expected.   So with that in mind, I think the best course for now will be to merge the PR, and tag a new release on a major version number.    I'll do that in the next few days and update here.

**Comment by xini** [comment]
@DorsetDigital any updates on this? Cheers

**Comment by DorsetDigital** [comment]
All done and tagged at v1.1.0   
Apologies for the delay!

**Comment by xini** [comment]
Great, thanks so much!

**Pull request merged**
